ALTER TABLE pelanggan 
ADD COLUMN kode_pelanggan VARCHAR(50) DEFAULT NULL,
ADD COLUMN alamat TEXT DEFAULT NULL,
ADD COLUMN jenis_customer VARCHAR(50) DEFAULT NULL,
ADD COLUMN flat_diskon DECIMAL(5,2) DEFAULT 0.00
AFTER telepon;

ALTER TABLE pelanggan_toko 
ADD COLUMN tanggal_daftar DATE DEFAULT NULL,
ADD COLUMN masa_berlaku INT(11) DEFAULT 0 COMMENT 'hari',
ADD COLUMN exp DATE DEFAULT NULL,
ADD COLUMN masa_tenggang INT(11) DEFAULT 0 COMMENT 'hari',
ADD COLUMN exp_poin DATE DEFAULT NULL,
ADD COLUMN poin_awal INT(11) DEFAULT 0,
ADD COLUMN poin_akhir INT(11) DEFAULT 0
AFTER limit_kredit;
