<?php
session_start();
require_once '../../inc/config.php';
require_once '../../inc/db.php';
require_once '../../inc/auth.php';
require_once '../../inc/csrf.php';
require_once '../../inc/pos_saas_schema.php';

requireLogin();
requireDevice();
ensure_pos_saas_schema($pos_db);

$tokoId = (int)($_SESSION['toko_id'] ?? 0);
$userNama = (string)($_SESSION['pengguna_nama'] ?? 'User');
$csrf = csrf_token();
$err = '';

if ($tokoId <= 0) {
    http_response_code(400);
    exit('Sesi toko tidak valid.');
}

function sql_literal($value): string {
    if ($value === null) return 'NULL';
    if (is_bool($value)) return $value ? '1' : '0';
    if (is_int($value) || is_float($value)) return (string)$value;
    $s = (string)$value;
    $s = strtr($s, [
        "\\" => "\\\\",
        "'" => "\\'",
        "\0" => "\\0",
        "\n" => "\\n",
        "\r" => "\\r",
        "\x1a" => "\\Z",
    ]);
    return "'" . $s . "'";
}

function get_tenant_tables(Database $db): array {
    $res = $db->query("
        SELECT TABLE_NAME
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND COLUMN_NAME = 'toko_id'
        GROUP BY TABLE_NAME
        ORDER BY TABLE_NAME
    ");
    $tables = [];
    while ($row = $res->fetch_assoc()) {
        $name = (string)($row['TABLE_NAME'] ?? '');
        if ($name !== '') $tables[] = $name;
    }
    return $tables;
}

function table_row_count_by_toko(Database $db, string $table, int $tokoId): int {
    $sql = "SELECT COUNT(*) AS cnt FROM `" . str_replace('`', '``', $table) . "` WHERE toko_id = ?";
    $st = $db->prepare($sql);
    $st->bind_param('i', $tokoId);
    $st->execute();
    $row = $st->get_result()->fetch_assoc();
    $st->close();
    return (int)($row['cnt'] ?? 0);
}

function build_tenant_backup_sql(Database $db, int $tokoId, string $generatedBy): string {
    $tables = get_tenant_tables($db);
    $date = date('Y-m-d H:i:s');
    $lines = [];
    $lines[] = "-- POS SaaS Tenant Backup";
    $lines[] = "-- Generated at: {$date}";
    $lines[] = "-- Generated by: {$generatedBy}";
    $lines[] = "-- Tenant toko_id: {$tokoId}";
    $lines[] = "SET NAMES utf8mb4;";
    $lines[] = "SET FOREIGN_KEY_CHECKS=0;";
    $lines[] = "START TRANSACTION;";
    $lines[] = "";

    foreach ($tables as $table) {
        $safeTable = "`" . str_replace('`', '``', $table) . "`";
        $sql = "SELECT * FROM {$safeTable} WHERE toko_id = ?";
        $st = $db->prepare($sql);
        $st->bind_param('i', $tokoId);
        $st->execute();
        $res = $st->get_result();

        $first = $res->fetch_assoc();
        if (!$first) {
            $st->close();
            continue;
        }

        $lines[] = "--";
        $lines[] = "-- TABLE {$table}";
        $lines[] = "--";
        $lines[] = "DELETE FROM {$safeTable} WHERE toko_id = {$tokoId};";

        $columns = array_keys($first);
        $colSql = array_map(static function ($c) {
            return "`" . str_replace('`', '``', (string)$c) . "`";
        }, $columns);
        $colList = implode(', ', $colSql);

        $rows = [$first];
        while ($r = $res->fetch_assoc()) {
            $rows[] = $r;
        }

        foreach ($rows as $row) {
            $vals = [];
            foreach ($columns as $c) {
                $vals[] = sql_literal($row[$c] ?? null);
            }
            $lines[] = "INSERT INTO {$safeTable} ({$colList}) VALUES (" . implode(', ', $vals) . ");";
        }
        $lines[] = "";
        $st->close();
    }

    $lines[] = "COMMIT;";
    $lines[] = "SET FOREIGN_KEY_CHECKS=1;";
    $lines[] = "";
    return implode("\n", $lines);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_protect_redirect();
    $action = (string)($_POST['action'] ?? '');

    if ($action === 'download_tenant_backup') {
        try {
            $sql = build_tenant_backup_sql($pos_db, $tokoId, $userNama);
            $filename = 'backup_toko_' . $tokoId . '_' . date('Ymd_His') . '.sql';
            header('Content-Type: application/sql; charset=utf-8');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            header('Content-Length: ' . strlen($sql));
            echo $sql;
            exit;
        } catch (Throwable $e) {
            $err = 'Gagal generate backup: ' . $e->getMessage();
        }
    }
}

$tables = get_tenant_tables($pos_db);
$tableStats = [];
$totalRows = 0;
foreach ($tables as $tb) {
    $cnt = table_row_count_by_toko($pos_db, $tb, $tokoId);
    $tableStats[] = ['table' => $tb, 'rows' => $cnt];
    $totalRows += $cnt;
}
?>
<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Maintenance Backup</title>
    <style>
        :root { --bg:#f8fafc; --border:#e2e8f0; --text:#0f172a; --muted:#64748b; }
        * { box-sizing: border-box; }
        body { margin:0; background:var(--bg); color:var(--text); font-family: Inter, sans-serif; }
        .wrap { max-width:1080px; margin:0 auto; padding:24px 16px; }
        .head { display:flex; justify-content:space-between; align-items:center; gap:10px; margin-bottom:14px; }
        .btn { text-decoration:none; border:1px solid var(--border); color:var(--text); background:#fff; border-radius:8px; padding:10px 14px; font-size:13px; }
        .btn-primary { border-color:#0f172a; background:#0f172a; color:#fff; cursor:pointer; font-weight:700; }
        .card { background:#fff; border:1px solid var(--border); border-radius:12px; padding:16px; margin-bottom:12px; }
        .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:10px; }
        .stat small { display:block; color:var(--muted); font-size:12px; margin-bottom:4px; }
        .stat strong { font-size:20px; }
        .muted { color:var(--muted); font-size:13px; }
        .err { border:1px solid #fca5a5; background:#fef2f2; color:#991b1b; border-radius:8px; padding:10px; margin-bottom:8px; }
        table { width:100%; border-collapse:collapse; font-size:13px; }
        th, td { border-bottom:1px solid var(--border); padding:9px 8px; text-align:left; }
        th { color:var(--muted); font-size:11px; text-transform:uppercase; }
        .num { text-align:right; }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="head">
            <h1 style="margin:0;font-size:24px;">Maintenance Backup</h1>
            <div style="display:flex;gap:8px;">
                <a class="btn" href="index.php">POS Utama</a>
                <a class="btn" href="maintenance_repair.php">Repair</a>
            </div>
        </div>

        <?php if ($err): ?><div class="err"><?= htmlspecialchars($err) ?></div><?php endif; ?>

        <div class="card">
            <div class="grid">
                <div class="stat"><small>Toko ID</small><strong><?= (int)$tokoId ?></strong></div>
                <div class="stat"><small>Tabel Tenant</small><strong><?= number_format(count($tableStats)) ?></strong></div>
                <div class="stat"><small>Total Baris Dibackup</small><strong><?= number_format($totalRows) ?></strong></div>
            </div>
            <p class="muted" style="margin:10px 0 0;">Backup ini khusus tenant aktif (`toko_id` saat ini), cocok untuk skenario POS SaaS multi-toko.</p>
        </div>

        <div class="card">
            <h3 style="margin-top:0;">Aksi Backup</h3>
            <form method="post">
                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>">
                <input type="hidden" name="action" value="download_tenant_backup">
                <button class="btn btn-primary" type="submit">Download SQL Backup Tenant</button>
            </form>
            <p class="muted" style="margin-top:10px;">File SQL berisi data tenant per tabel dengan pola `DELETE ... WHERE toko_id = X` lalu `INSERT`.</p>
        </div>

        <div class="card">
            <h3 style="margin-top:0;">Cakupan Tabel</h3>
            <table>
                <thead>
                    <tr>
                        <th>Tabel</th>
                        <th class="num">Rows (toko_id = <?= (int)$tokoId ?>)</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!$tableStats): ?>
                        <tr><td colspan="2" class="muted">Tidak ada tabel bertenant.</td></tr>
                    <?php else: foreach ($tableStats as $st): ?>
                        <tr>
                            <td><?= htmlspecialchars((string)$st['table']) ?></td>
                            <td class="num"><?= number_format((int)$st['rows']) ?></td>
                        </tr>
                    <?php endforeach; endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>
